default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: backend_development
  pool: 20
  username: student
  password: password

test:
  <<: *default
  adapter: postgresql
  host: localhost
  encoding: unicode
  database: backend_test
  pool: 20
  username: student
  password: password

production:
  <<: *default
  adapter: postgresql
  host: <%= ENV["BACKEND_DATABASE_HOST"] %>
  encoding: unicode
  database: backend_production
  username: backend
  password: <%= ENV["BACKEND_DATABASE_PASSWORD"] %>
