default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: backend_development
  username: postgres
  password: password
  host: localhost
  port: 5432

test:
  <<: *default
  database: backend_test
  username: postgres
  password: password
  host: localhost
  port: 5432

production:
  <<: *default
  database: backend_production
  username: backend
  password: <%= ENV["BACKEND_DATABASE_PASSWORD"] %>
  host: <%= ENV["BACKEND_DATABASE_HOST"] %>
  port: <%= ENV["BACKEND_DATABASE_PORT"] %>
